site_name: XJU Course Wiki
theme: 
  name: material
nav:
  - 首页: index.md
  - 软件工程: 
    - 课程简介: software-engineering/intro/main.md
    - 笔记: software-engineering/note/main.md
  - 习思想:
    - 课程简介: xi-mind/intro/main.md
    - 笔记: xi-mind/note/main.md
  - 离散数学:
    - 课程简介: discrete-math/intro/main.md
    - 笔记: discrete-math/note/main.md
  - 数据库:
    - 课程简介: database/intro/main.md
    - 笔记: database/note/main.md
  - 线性代数:
    - 课程简介: linear-algebra/intro/main.md
    - 笔记: linear-algebra/note/main.md
  - Linux:
    - 课程简介: linux/intro/main.md
    - 笔记: linux/note/main.md
    - 实验: linux/lab/main.md