site_name: XJU Course Wiki
theme: 
  name: material
nav:
  - 首页: index.md
  - 软件工程: 
    - 课程简介: software-engineering/intro/main.md
    - 笔记: software-engineering/note/main.md
  - 习思想:
    - 课程简介: xi-mind/intro/main.md
    - 笔记: xi-mind/note/main.md